development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: cat-holdings_development
  pool: 5
  username: postgres
  password: newgen

test:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: cat-holdings_test
  pool: 5
  username: postgres
  password: newgen
